/// Flutter icons Sportive
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Sportive
///      fonts:
///       - asset: fonts/Sportive.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Sportive {
  Sportive._();

  static const _kFontFam = 'Sportive';
  static const String _kFontPkg = null;

  static const IconData transferNewsIcon =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Team =
      IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stats =
      IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData predict =
      IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
